// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppDockerTeste.Data;

#nullable disable

namespace WebAppDockerTeste.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppDockerTeste.Models.Batman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Batmans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b970630d-91ef-4881-a862-c6a5ef5807d5"),
                            Name = "Batman1"
                        },
                        new
                        {
                            Id = new Guid("0f2e7396-5cef-4541-aaf9-95b92c789122"),
                            Name = "Batman2"
                        },
                        new
                        {
                            Id = new Guid("74226486-7f03-4c66-8473-6453e6f32a8b"),
                            Name = "Batman3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
